# Generated by Django 2.2.28 on 2023-04-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_testing123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testing23',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test34', models.BigIntegerField()),
            ],
        ),
    ]
